/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ticketapp;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.System.console;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Tetsuya
 */
public class TicketGUI extends javax.swing.JFrame {

    ArrayList<Ticket> tickets;
    
    
    /** Creates new form TicketGUI */
    public TicketGUI() {
        initComponents();
        saveBtn.setToolTipText("Click this button to save ticket details to file");
        viewBtn.setToolTipText("Click this button to view ticket details entered");
        resetBtn.setToolTipText("Click this button to start over");
        LoadBtn.setToolTipText("Click this button to load previously saved ticket details");
        buyTickets.setToolTipText("Click this button to buy tickets");
        addBTN.setToolTipText("Click this enter ticket details");
        add2Btn.setToolTipText("Click this button to add another ticket");
        // hide on load
        
        tickets = new ArrayList<>();
        
        firstNameTF.setVisible(false);
        firstNameLB.setVisible(false);
        
        lastNameTF.setVisible(false);
        lastNameLB.setVisible(false);
        
        ageTF.setVisible(false);
        ageLB.setVisible(false);
        
        studentNoTF.setVisible(false);
        studentNoLB.setVisible(false);
        
        seatNoTF.setVisible(false);
        seatNoLB.setVisible(false);
        
        ticketDetailsLB.setVisible(false);
        
      
        // ticket prive
        ticketPriceTF.setVisible(false);
        jLabel1.setVisible(false);
        
        // teir 
        ticketTierLB.setVisible(false);
        lowerTierBtn.setVisible(false);
        middleTierBtn.setVisible(false);
        higherTierBtn.setVisible(false);
        
        
       // buttions for file writing 
        addBTN.setVisible(false);
        viewBtn.setVisible(false);
     //   LoadBtn.setVisible(false);
        saveBtn.setVisible(false);
        add2Btn.setVisible(false);
        
           ticketTypeLB.setVisible(false);
        adultRB.setVisible(false);
        childRB.setVisible(false);
        seniorRB.setVisible(false);
        studentRB.setVisible(false); 
        
        resetBtn.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketTypeBG = new javax.swing.ButtonGroup();
        ticketTierBG = new javax.swing.ButtonGroup();
        adultRB = new javax.swing.JRadioButton();
        childRB = new javax.swing.JRadioButton();
        seniorRB = new javax.swing.JRadioButton();
        studentRB = new javax.swing.JRadioButton();
        lowerTierBtn = new javax.swing.JRadioButton();
        higherTierBtn = new javax.swing.JRadioButton();
        middleTierBtn = new javax.swing.JRadioButton();
        firstNameTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        studentNoTF = new javax.swing.JTextField();
        firstNameLB = new javax.swing.JLabel();
        lastNameLB = new javax.swing.JLabel();
        ageLB = new javax.swing.JLabel();
        studentNoLB = new javax.swing.JLabel();
        ticketTypeLB = new javax.swing.JLabel();
        ticketTierLB = new javax.swing.JLabel();
        ticketDetailsLB = new javax.swing.JLabel();
        headerLB = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        seatNoTF = new javax.swing.JTextField();
        seatNoLB = new javax.swing.JLabel();
        ticketPriceTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        LoadBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        buyTickets = new javax.swing.JButton();
        add2Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ticketTypeBG.add(adultRB);
        adultRB.setText("Adult");
        adultRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultRBActionPerformed(evt);
            }
        });

        ticketTypeBG.add(childRB);
        childRB.setText("Child");
        childRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childRBActionPerformed(evt);
            }
        });

        ticketTypeBG.add(seniorRB);
        seniorRB.setText("Senior");
        seniorRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorRBActionPerformed(evt);
            }
        });

        ticketTypeBG.add(studentRB);
        studentRB.setText("Student");
        studentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRBActionPerformed(evt);
            }
        });

        ticketTierBG.add(lowerTierBtn);
        lowerTierBtn.setText("Lower");
        lowerTierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerTierBtnActionPerformed(evt);
            }
        });

        ticketTierBG.add(higherTierBtn);
        higherTierBtn.setText("Higher");
        higherTierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherTierBtnActionPerformed(evt);
            }
        });

        ticketTierBG.add(middleTierBtn);
        middleTierBtn.setText("Middle");
        middleTierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleTierBtnActionPerformed(evt);
            }
        });

        lastNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTFActionPerformed(evt);
            }
        });

        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });

        firstNameLB.setText("First Name:");

        lastNameLB.setText("Last Name:");

        ageLB.setText("Age:");

        studentNoLB.setText("Student Number:");

        ticketTypeLB.setText("Type:");

        ticketTierLB.setText("Tier:");

        ticketDetailsLB.setText("Ticket Details:");

        headerLB.setText("Ticket Booking System");

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        seatNoLB.setText("Seat No.");

        ticketPriceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketPriceTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Ticket Price:");

        saveBtn.setText("Save");
        saveBtn.setToolTipText("");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View Details");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        LoadBtn.setText("Load");
        LoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        buyTickets.setText("Buy Tickets");
        buyTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketsActionPerformed(evt);
            }
        });

        add2Btn.setText("Add another ticket");
        add2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adultRB)
                            .addComponent(ticketTypeLB)
                            .addComponent(childRB)
                            .addComponent(studentRB)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seniorRB)
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(middleTierBtn)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ticketTierLB)
                                            .addComponent(lowerTierBtn)))
                                    .addComponent(higherTierBtn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(studentNoLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ageLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lastNameLB, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ticketDetailsLB)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(buyTickets)
                                .addGap(67, 67, 67)
                                .addComponent(LoadBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add2Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(saveBtn))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(seatNoLB, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ticketPriceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addComponent(seatNoTF))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBTN)
                                .addGap(32, 32, 32)
                                .addComponent(viewBtn)))))
                .addGap(18, 18, 18)
                .addComponent(resetBtn)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(headerLB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLB)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ticketTypeLB)
                            .addComponent(ticketDetailsLB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adultRB)
                            .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(childRB)
                            .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLB)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(seniorRB)
                                .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ticketTierLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lowerTierBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(middleTierBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(higherTierBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentRB)
                    .addComponent(studentNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNoLB))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatNoLB)
                    .addComponent(buyTickets)
                    .addComponent(LoadBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(viewBtn)
                    .addComponent(add2Btn))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(resetBtn))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adultRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultRBActionPerformed
        // TODO add your handling code here:
        
        //firstNameTF.setVisible(true);
        //firstNameLB.setVisible(true);
        
        //lastNameTF.setVisible(true);
        //lastNameLB.setVisible(true);
        
        //ageTF.setVisible(false);
        //ageLB.setVisible(false);
        
   //     studentNoTF.setVisible(false);
      //  studentNoLB.setVisible(false);
        
   //     seatNoTF.setVisible(true);
    //    seatNoLB.setVisible(true);
        
        //double ticketPrice;
        //ticketPrice = 50.00;
        //ticketPriceTF.setText(Double.toString(ticketPrice));
       
        ticketTierLB.setVisible(true);
        lowerTierBtn.setVisible(true);
        middleTierBtn.setVisible(true);
        higherTierBtn.setVisible(true);
                
    }//GEN-LAST:event_adultRBActionPerformed

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ageTFActionPerformed

    private void childRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childRBActionPerformed
        // TODO add your handling code here:
        
        ticketTierLB.setVisible(true);
        lowerTierBtn.setVisible(true);
        middleTierBtn.setVisible(true);
        higherTierBtn.setVisible(true);
       
    }//GEN-LAST:event_childRBActionPerformed

    private void seniorRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorRBActionPerformed
        // TODO add your handling code here:
        ticketTierLB.setVisible(true);
        lowerTierBtn.setVisible(true);
        middleTierBtn.setVisible(true);
        higherTierBtn.setVisible(true);
        
        
    }//GEN-LAST:event_seniorRBActionPerformed

    private void studentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRBActionPerformed
        // TODO add your handling code here:
        ticketTierLB.setVisible(true);
        lowerTierBtn.setVisible(true);
        middleTierBtn.setVisible(true);
        higherTierBtn.setVisible(true);
        
        
    }//GEN-LAST:event_studentRBActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        
        String firstName, lastName, seatNo, type;
        double ticketPrice;
        
        int age;
        
        int studentNo;
        
        Ticket t;
        
        firstName = firstNameTF.getText();
        lastName = lastNameTF.getText();
        seatNo = seatNoTF.getText();
        ticketPrice = Double.parseDouble(ticketPriceTF.getText());
        
        if(adultRB.isSelected()){
            type="Adult";
            t = new Adult ( seatNo, firstName, lastName, ticketPrice);
            
        }else if(childRB.isSelected()){
            type="Child";
            age = Integer.parseInt(ageTF.getText());
            t = new Child( seatNo, firstName, lastName, ticketPrice, age);
            
            
        }else if(seniorRB.isSelected()){
            type="Senior";
            age = Integer.parseInt(ageTF.getText());
            t = new Senior ( seatNo, firstName, lastName, ticketPrice, age);
        
        }else if (studentRB.isSelected()){
            type="Student";
            studentNo = Integer.parseInt(studentNoTF.getText());
            t = new Student( seatNo, firstName, lastName, ticketPrice, studentNo);
        }else{
            type = null;
            seatNo = null;
            t = new Ticket(seatNo, firstName, lastName, ticketPrice);
        }
        
        firstNameTF.setText("");
        lastNameTF.setText("");
        seatNoTF.setText("");
        ticketPriceTF.setText("");
        
        ageTF.setText("");
        
        studentNoTF.setText("");     
        
        System.out.println(t);
        tickets.add(t);     
        
        viewBtn.setVisible(true);
        //LoadBtn.setVisible(false);
        saveBtn.setVisible(true);
        add2Btn.setVisible(true);
        
        firstNameTF.setVisible(false);
        firstNameLB.setVisible(false);
        
        lastNameTF.setVisible(false);
        lastNameLB.setVisible(false);
        
        ageTF.setVisible(false);
        ageLB.setVisible(false);
        
        studentNoTF.setVisible(false);
        studentNoLB.setVisible(false);
        
        seatNoTF.setVisible(false);
        seatNoLB.setVisible(false);
        
        ticketDetailsLB.setVisible(false);
    
        ticketPriceTF.setVisible(false);
        jLabel1.setVisible(false);
        addBTN.setVisible(false);
    }//GEN-LAST:event_addBTNActionPerformed

    private void lastNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTFActionPerformed

    private void lowerTierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerTierBtnActionPerformed
        // TODO add your handling code here:

        int first;
        String seatM ="";
        first =134 + (int)(Math.random()*421);
        seatM += first +134;
        seatNoTF.setText(seatM);
        
        double ticketPrice;       
        ticketPrice=0;    
                
        // if both and lower are selected then give price and show fields and hide others
         if(adultRB.isSelected() && lowerTierBtn.isSelected()){
           ticketPrice = 50.00;
            firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(false);
            ageLB.setVisible(false);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Lower Tier Adult Ticket");
   
         }
         
         if(childRB.isSelected() && lowerTierBtn.isSelected()){
           ticketPrice = 15.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(true);
            ageLB.setVisible(true);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Lower Tier Child Ticket");
   
            
         }
         
         if(seniorRB.isSelected() && lowerTierBtn.isSelected()){
           ticketPrice = 40.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(true);
            ageLB.setVisible(true);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Lower Tier Senior Ticket");
   
            
         }
         if(studentRB.isSelected() && lowerTierBtn.isSelected()){
           ticketPrice = 30.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(false);
            ageLB.setVisible(false);
        
            studentNoTF.setVisible(true);
            studentNoLB.setVisible(true);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            headerLB.setText("Lower Tier Student Ticket");
   
         }
         
        ticketPriceTF.setText(Double.toString(ticketPrice));

        ticketTypeLB.setVisible(false);
        adultRB.setVisible(false);
        childRB.setVisible(false);
        seniorRB.setVisible(false);
        studentRB.setVisible(false);
        
        ticketTierLB.setVisible(false);
        lowerTierBtn.setVisible(false);
        middleTierBtn.setVisible(false);
        higherTierBtn.setVisible(false);
        
        
    }//GEN-LAST:event_lowerTierBtnActionPerformed

    private void middleTierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleTierBtnActionPerformed
        // TODO add your handling code here:
        
        int first;
        String seatM ="";
        first =134 + (int)(Math.random()*421);
        seatM += first +134;
        seatNoTF.setText(seatM);
        
        double ticketPrice;       
        ticketPrice=0;
        
        
         // if both and lower are selected then give price and show fields and hide others
         if(adultRB.isSelected() && middleTierBtn.isSelected()){
           ticketPrice = 65.00;
            firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(false);
            ageLB.setVisible(false);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Middle Tier Adult Ticket");
   
         }
         
         if(childRB.isSelected() && middleTierBtn.isSelected()){
           ticketPrice = 25.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(true);
            ageLB.setVisible(true);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Middle Tier Child Ticket");
   
            
         }
         
         if(seniorRB.isSelected() && middleTierBtn.isSelected()){
           ticketPrice = 50.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(true);
            ageLB.setVisible(true);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Middle Tier Senior Ticket");
   
            
         }
         if(studentRB.isSelected() && middleTierBtn.isSelected()){
           ticketPrice = 40.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(false);
            ageLB.setVisible(false);
        
            studentNoTF.setVisible(true);
            studentNoLB.setVisible(true);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            headerLB.setText("Middle Tier Student Ticket");
   
         }
         
        ticketPriceTF.setText(Double.toString(ticketPrice));

        ticketTypeLB.setVisible(false);
        adultRB.setVisible(false);
        childRB.setVisible(false);
        seniorRB.setVisible(false);
        studentRB.setVisible(false);
        
        ticketTierLB.setVisible(false);
        lowerTierBtn.setVisible(false);
        middleTierBtn.setVisible(false);
        higherTierBtn.setVisible(false);
        
        ticketPriceTF.setText(Double.toString(ticketPrice));
    }//GEN-LAST:event_middleTierBtnActionPerformed

    private void higherTierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherTierBtnActionPerformed
        // TODO add your handling code here:
        
        int first;
        String seatM ="";
        first =134 + (int)(Math.random()*421);
        seatM += first +134;
        seatNoTF.setText(seatM);
        
        double ticketPrice;       
        ticketPrice=0;
        
         // if both and lower are selected then give price and show fields and hide others
         if(adultRB.isSelected() && higherTierBtn.isSelected()){
           ticketPrice = 80.00;
            firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(false);
            ageLB.setVisible(false);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Higher Tier Adult Ticket");
   
         }
         
         if(childRB.isSelected() && higherTierBtn.isSelected()){
           ticketPrice = 35.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(true);
            ageLB.setVisible(true);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Higher Tier Child Ticket");
   
            
         }
         
         if(seniorRB.isSelected() && higherTierBtn.isSelected()){
           ticketPrice = 60.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(true);
            ageLB.setVisible(true);
        
            studentNoTF.setVisible(false);
            studentNoLB.setVisible(false);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            
            headerLB.setText("Higher Tier Senior Ticket");
   
            
         }
         if(studentRB.isSelected() && higherTierBtn.isSelected()){
           ticketPrice = 50.00;
             firstNameTF.setVisible(true);
            firstNameLB.setVisible(true);
        
            lastNameTF.setVisible(true);
            lastNameLB.setVisible(true);
        
            ageTF.setVisible(false);
            ageLB.setVisible(false);
        
            studentNoTF.setVisible(true);
            studentNoLB.setVisible(true);
        
            seatNoTF.setVisible(true);
            seatNoLB.setVisible(true);
            
            ticketPriceTF.setVisible(true);
            jLabel1.setVisible(true);
            
            addBTN.setVisible(true);
            headerLB.setText("Higher Tier Student Ticket");
   
         }
         
        ticketPriceTF.setText(Double.toString(ticketPrice));

        ticketTypeLB.setVisible(false);
        adultRB.setVisible(false);
        childRB.setVisible(false);
        seniorRB.setVisible(false);
        studentRB.setVisible(false);
        
        ticketTierLB.setVisible(false);
        lowerTierBtn.setVisible(false);
        middleTierBtn.setVisible(false);
        higherTierBtn.setVisible(false);
        
        ticketPriceTF.setText(Double.toString(ticketPrice));
    }//GEN-LAST:event_higherTierBtnActionPerformed

    private void ticketPriceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketPriceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketPriceTFActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
               
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        try{            
            outFile = new File("ticketfile.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);
            
            for (Ticket tic : tickets) {
                
                if (tic instanceof Adult) {
                    Adult myAdult = (Adult) tic;
                    bw.write(myAdult.printDetails());
                    bw.newLine();
                } else if (tic instanceof Child) {
                    Child myChild = (Child) tic;
                    bw.write(myChild.printDetails());
                    bw.newLine();
                } else if (tic instanceof Senior) {
                    Senior mySenior = (Senior) tic;
                    bw.write(mySenior.printDetails());
                    bw.newLine();
                }else if(tic instanceof Student){
                    Student myStudent = (Student) tic;
                    bw.write(myStudent.printDetails());
                    bw.newLine();
                }else {
                    bw.write(tic.printDetails());
                    bw.newLine();
                }
            }
            bw.close();
        }
        catch(IOException t){
            System.out.println(t.toString()+ "Error writing to File");
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        tickets.forEach((tic) -> {
            if (tic instanceof Adult) {
                Adult myAdult = (Adult) tic;
                JOptionPane.showMessageDialog(null, myAdult.printDetails());
            } else if (tic instanceof Child) {
                Child myChild = (Child) tic;
                JOptionPane.showMessageDialog(null, myChild.printDetails());
            } else if (tic instanceof Senior) {
                Senior mySenior = (Senior) tic;
                JOptionPane.showMessageDialog(null, mySenior.printDetails());
            }else if(tic instanceof Student){
                Student myStudent =(Student) tic;
                JOptionPane.showMessageDialog(null, myStudent.printDetails());
            } 
            
            else {
                JOptionPane.showMessageDialog(null, tic.printDetails());
            }
        });
        
    }//GEN-LAST:event_viewBtnActionPerformed

    private void LoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBtnActionPerformed
        // TODO add your handling code here:
        
        String data;
        File readFile;
        FileReader fr;
        BufferedReader br;
        
        try {
            readFile = new File("ticketfile.txt");
            fr = new FileReader(readFile);
            br = new BufferedReader(fr);

            data = br.readLine();
            while (data != null) {                
                JOptionPane.showMessageDialog(null, data);
                data = br.readLine();               
             }

            br.close();

        } catch (IOException t) {
            System.out.println("Error reading from file: " + t);
        }
    }//GEN-LAST:event_LoadBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // restart
        
        tickets = new ArrayList<>();
        
        firstNameTF.setVisible(false);
        firstNameLB.setVisible(false);
        
        lastNameTF.setVisible(false);
        lastNameLB.setVisible(false);
        
        ageTF.setVisible(false);
        ageLB.setVisible(false);
        
        studentNoTF.setVisible(false);
        studentNoLB.setVisible(false);
        
        seatNoTF.setVisible(false);
        seatNoLB.setVisible(false);
        
        ticketDetailsLB.setVisible(false);
        
      
        // ticket prive
        ticketPriceTF.setVisible(false);
        jLabel1.setVisible(false);
        
        // teir 
        ticketTierLB.setVisible(false);
        lowerTierBtn.setVisible(false);
        middleTierBtn.setVisible(false);
        higherTierBtn.setVisible(false);
        
        
       // buttions for file writing 
        addBTN.setVisible(false);
        viewBtn.setVisible(false);
        LoadBtn.setVisible(false);
        saveBtn.setVisible(false);
        
         ticketTypeLB.setVisible(false);
        adultRB.setVisible(false);
        childRB.setVisible(false);
        seniorRB.setVisible(false);
        studentRB.setVisible(false);
        
        buyTickets.setVisible(true);
        LoadBtn.setVisible(true);
        resetBtn.setVisible(false);
        add2Btn.setVisible(false);
        
        headerLB.setText("Ticket Booking System");
       
   
    }//GEN-LAST:event_resetBtnActionPerformed

    private void buyTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketsActionPerformed
        // TODO add your handling code here:
        ticketTypeLB.setVisible(true);
        adultRB.setVisible(true);
        childRB.setVisible(true);
        seniorRB.setVisible(true);
        studentRB.setVisible(true);
        
        buyTickets.setVisible(false);
        
        resetBtn.setVisible(true);
       // viewBtn.setVisible(false);
       LoadBtn.setVisible(false);
    }//GEN-LAST:event_buyTicketsActionPerformed

    private void add2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2BtnActionPerformed
        // TODO add your handling code here:
        
        ticketTypeLB.setVisible(true);
        adultRB.setVisible(true);
        childRB.setVisible(true);
        seniorRB.setVisible(true);
        studentRB.setVisible(true);
        
        buyTickets.setVisible(false);
        
        resetBtn.setVisible(true);
       // viewBtn.setVisible(false);
        LoadBtn.setVisible(false);
        addBTN.setVisible(false);
        viewBtn.setVisible(false);
        LoadBtn.setVisible(false);
        saveBtn.setVisible(false);
        add2Btn.setVisible(false);
    }//GEN-LAST:event_add2BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadBtn;
    private javax.swing.JButton add2Btn;
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton adultRB;
    private javax.swing.JLabel ageLB;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton buyTickets;
    private javax.swing.JRadioButton childRB;
    private javax.swing.JLabel firstNameLB;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JLabel headerLB;
    private javax.swing.JRadioButton higherTierBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastNameLB;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JRadioButton lowerTierBtn;
    private javax.swing.JRadioButton middleTierBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel seatNoLB;
    private javax.swing.JTextField seatNoTF;
    private javax.swing.JRadioButton seniorRB;
    private javax.swing.JLabel studentNoLB;
    private javax.swing.JTextField studentNoTF;
    private javax.swing.JRadioButton studentRB;
    private javax.swing.JLabel ticketDetailsLB;
    private javax.swing.JTextField ticketPriceTF;
    private javax.swing.ButtonGroup ticketTierBG;
    private javax.swing.JLabel ticketTierLB;
    private javax.swing.ButtonGroup ticketTypeBG;
    private javax.swing.JLabel ticketTypeLB;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

}
